"""empty message

Revision ID: 23332b356830
Revises: 17e5a0dbb140
Create Date: 2023-05-25 19:21:03.269557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23332b356830'
down_revision = '17e5a0dbb140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('introduce', sa.Text(), nullable=True),
    sa.Column('big_img', sa.String(length=255), nullable=True),
    sa.Column('small_img', sa.String(length=255), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('is_promote', sa.Integer(), nullable=True),
    sa.Column('hot_number', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('cid_one', sa.Integer(), nullable=True),
    sa.Column('cid_two', sa.Integer(), nullable=True),
    sa.Column('cid_three', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid_one'], ['t_category.id'], ),
    sa.ForeignKeyConstraint(['cid_three'], ['t_category.id'], ),
    sa.ForeignKeyConstraint(['cid_two'], ['t_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('pay_status', sa.Integer(), nullable=True),
    sa.Column('is_send', sa.Integer(), nullable=True),
    sa.Column('fapiao_title', sa.String(length=255), nullable=True),
    sa.Column('fapiao_content', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['t_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_picture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('path', sa.String(length=255), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['t_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_product_attr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('aid', sa.Integer(), nullable=True),
    sa.Column('val', sa.String(length=256), nullable=True),
    sa.Column('_type', sa.Enum('static', 'dynamic'), nullable=True),
    sa.ForeignKeyConstraint(['aid'], ['t_attribute.id'], ),
    sa.ForeignKeyConstraint(['pid'], ['t_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_express',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oid', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=256), nullable=True),
    sa.Column('update_time', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['oid'], ['t_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_order_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('oid', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['oid'], ['t_order.id'], ),
    sa.ForeignKeyConstraint(['pid'], ['t_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_order_detail')
    op.drop_table('t_express')
    op.drop_table('t_product_attr')
    op.drop_table('t_picture')
    op.drop_table('t_order')
    op.drop_table('t_product')
    # ### end Alembic commands ###
