"""empty message

Revision ID: 3c62dfd278cf
Revises: 736259f5d11a
Create Date: 2023-05-11 14:11:34.442254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c62dfd278cf'
down_revision = '736259f5d11a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=11),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_users', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(length=128),
               type_=mysql.VARCHAR(length=11),
               existing_nullable=True)

    # ### end Alembic commands ###
