###增加分类属性
POST  http://127.0.0.1:5000/attributes/
Content-Type: application/json

{
    "name":"颜色类型",
    "_type":"dynamic",
    "val":"深空黑,白色,红色",
    "cid":83
}

###获取分类属性列表
GET http://127.0.0.1:5000/attributes/?cid=65&_type=static

###根据分类id获取分类属性
GET http://127.0.0.1:5000/attribute/10/

###修改分类属性
PUT http://127.0.0.1:5000/attribute/23/
Content-Type: application/json

{
    "val":"天鹅白"
}
###删除分类属性
DELETE http://127.0.0.1:5000/attribute/24/